# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    weight: 10
    identifier: Home
  - name: About
    url: ""
    weight: 20
    identifier: About
 # - name: "In 1 minute"
  #  url: '#slider'
  #  weight: 12
  #  parent: Home
  - name: "What we do"
    url: "/authors/admin/"
    weight: 21
    parent: About
  - name: "Organisation"
    url: '/organisation/'
    weight: 22
    parent: About
  - name: Contributors
    url: '#contributors'
    weight: 23
    parent: About
  - name: "Projects â†´"
    url: "/project/"
    weight: 24
    parent: About
  - name: ğŸ‡ªğŸ‡º Listen Local
    url: '/project/listen-local/'
    weight: 26
    parent: About
  - name: ğŸ‡ªğŸ‡º Open Music Europe
    url: '/project/open-music-europe/'
    weight: 27
    parent: About
  - name: ğŸ‡ªğŸ‡º Music Eviota
    url: '#projects'
    weight: 28
    parent: About
    url: ../project/musiceviota/
  - name: Topics
    url: '#tags'
    weight: 29
    parent: About  
  - name: Data
    url: '#pillars'
    weight: 40
    identifier: Data
  - name: ğŸ›ï¸ Music & Economy
    url: '#pillars'
    weight: 41
    parent: Data
  - name: ğŸ›ï¸ Diversity & Circulation
    url: '#pillars'
    weight: 42
    parent: Data
  - name: ğŸ›ï¸ Music & Society
    url: '#pillars'
    weight: 43
    parent: Data
  - name: ğŸ›ï¸ Music Tech & Innovation
    url: '#pillars'
    weight: 44
    parent: Data
  - name: ğŸ“– Open Science Repository
    url: 'https://zenodo.org/communities/music_observatory'
    weight: 46
    parent: Data
  - name: ğŸ™ï¸ Open Music Collections
    weight: 47
    url: https://www.opencollections.net/collections/music/
    parent: Data
  - name: Data collection
    url: ../collection/
    weight: 48
    parent: Data
  - name: ğŸ–¥ï¸ API
    url: '#data'
    weight: 49
    parent: Data
  - name: Solutions
    url: '#services'
    weight: 50
    identifier: Solutions
  - name: Applications
    url: 'apps/'
    weight: 51
    parent: Solutions
  - name: Software
    url: '#releases'
    weight: 52
    parent: Solutions
#  - name: Use cases
#    url: '#usecase'
#    weight: 34
    parent: Solutions
  - name: Code
    url: '/category/r-bloggers/'
    weight: 54
    parent: Solutions
  - name: Publications
    url: '#featured'
    weight: 60
    identifier: Publications
  - name: Featured
    url: '#featured'
    weight: 60
    parent: Publications
  - name: All Publications
    url: '#publications'
    weight: 62
    parent: Publications
  - name: Contact
    url: '#contact'
    weight: 90
    identifier: Contact
  - name: Get in touch
    url: '#contact'
    weight: 91
    parent: Contact
  - name: Public talks
    url: '#talks'
    weight: 92
    parent: Contact

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
